create table element_list (
	id INTEGER PRIMARY KEY,
	primary_element TEXT,
	secondary_element TEXT,
	underbarrel BOOLEAN
);

CREATE TABLE unique_shields (
    id INTEGER,
    manufacturer TEXT,
	unique_perk TEXT,
    shield_name TEXT
);

CREATE TABLE part_list (
    manufacturer TEXT,
    weapon_type TEXT,
    id INTEGER,
    part_type TEXT,
    part_string TEXT,
    model_name TEXT,
    stats TEXT,
    effects TEXT,
    requirements TEXT
);

CREATE TABLE type_and_manufacturer (
    id INTEGER PRIMARY KEY,
    manufacturer TEXT,
    item_type TEXT
);

CREATE TABLE shield_parts (
    id INTEGER,
    name TEXT,
    perk_type TEXT,
    shield_type TEXT,
    slot INTEGER
);

insert into element_list 
(id, primary_element, secondary_element, underbarrel)
values 
(1, 'Kinetic', Null, FALSE),
(2, 'Kinetic', Null, FALSE),
(3, 'Kinetic', Null, FALSE),
(4, 'Kinetic', Null, FALSE),
(5, 'Shock', 'Radiation', FALSE),
(6, 'Shock', 'Fire', FALSE),
(7, 'Shock', 'Cryo', FALSE),
(8, 'Shock', 'Corrosive', FALSE),
(9, 'Radiation', 'Shock', FALSE),
(10, 'Corrosive', Null, FALSE),
(11, 'Cryo', Null, FALSE),
(12, 'Fire', Null, FALSE),
(13, 'Radiation', Null, FALSE),
(14, 'Shock', Null, FALSE),
(15, 'Radiation', 'Fire', FALSE),
(16, 'Radiation', 'Cryo', FALSE),
(17, 'Radiation', 'Corrosive', FALSE),
(18, 'Fire', 'Radiation', FALSE),
(19, 'Fire', 'Cryo', FALSE),
(20, 'Fire', 'Corrosive', FALSE),
(21, 'Cryo', 'Shock', FALSE),
(22, 'Cryo', 'Radiation', FALSE),
(23, 'Cryo', 'Fire', FALSE),
(24, 'Cryo', 'Corrosive', FALSE),
(25, 'Corrosive', 'Shock', FALSE),
(26, 'Corrosive', 'Radiation', FALSE),
(27, 'Corrosive', 'Fire', FALSE),
(28, 'Corrosive', 'Cryo', FALSE),
(29, 'Shock', 'Radiation', TRUE),
(30, 'Fire', 'Radiation', TRUE),
(31, 'Cryo', 'Radiation', TRUE),
(32, 'Corrosive', 'Radiation', TRUE),
(33, 'Radiation', 'Corrosive', TRUE),
(34, 'Shock', 'Corrosive', TRUE),
(35, 'Fire', 'Corrosive', TRUE),
(36, 'Cryo', 'Corrosive', TRUE),
(37, 'Radiation', 'Cryo', TRUE),
(38, 'Shock', 'Cryo', TRUE),
(39, 'Fire', 'Cryo', TRUE),
(40, 'Corrosive', 'Cryo', TRUE),
(41, 'Radiation', 'Fire', TRUE),
(42, 'Cryo', 'Fire', TRUE),
(43, 'Shock', 'Fire', TRUE),
(44, 'Corrosive', 'Fire', TRUE),
(45, 'Radiation', 'Shock', TRUE),
(46, 'Cryo', 'Shock', TRUE),
(47, 'Corrosive', 'Shock', TRUE),
(48, 'Fire', 'Shock', FALSE),
(49, 'Fire', 'Shock', TRUE),
(50, 'Kinetic', Null, FALSE);



-- part list inserts are handled by the bot at initiation and on an adhoc basis.;

insert into type_and_manufacturer 
(id, manufacturer, item_type)
values 
(2, 'daedalus', 'pistol'),
(3, 'jakobs', 'pistol'),
(4, 'order', 'pistol'),
(5, 'tediore', 'pistol'),
(6, 'torgue', 'pistol'),
(7, 'ripper', 'shotgun'),
(8, 'daedalus', 'shotgun'),
(9, 'jakobs', 'shotgun'),
(10, 'maliwan', 'shotgun'),
(11, 'tediore', 'shotgun'),
(12, 'torgue', 'shotgun'),
(13, 'daedalus', 'assault_rifle'),
(14, 'tediore', 'assault_rifle'),
(15, 'order', 'assault_riffle'),
(16, 'vladof', 'sniper'),
(17, 'torgue', 'assault_rifle'),
(18, 'vladof', 'assault_rifle'),
(19, 'ripper', 'smg'),
(20, 'daedalus', 'smg'),
(21, 'maliwan', 'smg'),
(22, 'vladof', 'smg'),
(23, 'ripper', 'sniper'),
(24, 'jakobs', 'sniper'),
(25, 'maliwan', 'sniper'),
(26, 'order', 'sniper'),
(27, 'jakobs', 'assault_rifle'),
(254, 'siren', 'class_mod'),
(255, 'forgeknight', 'class_mod'),
(256, 'exo_soldier', 'class_mod'),
(259, 'gravitar', 'class_mod'),
(261, 'torgue', 'repair_kit'),
(263, 'maliwan', 'gadget'),
(264, 'hyperion', 'enhancement'),
(265, 'jakobs', 'repair_kit'),
(266, 'maliwan', 'repair_kit'),
(267, 'jakobs', 'gadget'),
(268, 'jakobs', 'enhancement'),
(269, 'vladof', 'repair_kit'),
(270, 'daedalus', 'gadget'),
(271, 'maliwan', 'enhancement'),
(272, 'order', 'gadget'),
(273, 'torgue', 'heavy'),
(274, 'ripper', 'repair_kit'),
(275, 'ripper', 'heavy'),
(277, 'daedalus', 'repair_kit'),
(278, 'ripper', 'gadget'),
(279, 'maliwan', 'shield'),
(281, 'order', 'enhancement'),
(282, 'vladof', 'heavy'),
(283, 'vladof', 'shield'),
(284, 'atlas', 'enhancement'),
(285, 'order', 'repair_kit'),
(286, 'cov', 'enhancement'),
(287, 'tediore', 'shield'),
(289, 'maliwan', 'heavy'),
(290, 'tediore', 'repair_kit'),
(291, 'vladof', 'gadget'),
(292, 'tediore', 'enhancement'),
(293, 'order', 'shield'),
(296, 'ripper', 'enhancement'),
(298, 'torgue', 'gadget'),
(299, 'daedalus', 'enhancement'),
(300, 'ripper', 'shield'),
(303, 'torgue', 'enhancement'),
(306, 'jakobs', 'shield'),
(310, 'vladof', 'enhancement'),
(311, 'tediore', 'gadget'),
(312, 'daedalus', 'shield'),
(321, 'torgue', 'shield');



insert into shield_parts 
(id, name, perk_type, shield_type, slot)
values 
(1, 'God Killer', 'Firmware', 'General', null),
(2, 'Reel Big Fist', 'Firmware', 'General', null),
(3, 'Lifeblood', 'Firmware', 'General', null),
(4, 'Airstrike', 'Firmware', 'General', null),
(5, 'High Caliber', 'Firmware', 'General', null),
(6, 'Gadget Ahoy', 'Firmware', 'General', null),
(7, 'Baker', 'Firmware', 'General', null),
(8, 'Oscar Mike', 'Firmware', 'General', null),
(9, 'Rubberband Man', 'Firmware', 'General', null),
(10, 'Deadeye', 'Firmware', 'General', null),
(11, 'Action Fist', 'Firmware', 'General', null),
(12, 'GooJFC', 'Firmware', 'General', null),
(13, 'Atlas E.X.', 'Firmware', 'General', null),
(14, 'Atlas Infinum', 'Firmware', 'General', null),
(15, 'Trickshot', 'Firmware', 'General', null),
(16, 'Jacked', 'Firmware', 'General', null),
(17, 'Get Throwin', 'Firmware', 'General', null),
(18, 'Heating Up', 'Firmware', 'General', null),
(19, 'Bullets to Spare', 'Firmware', 'General', null),
(20, 'Daed-dy O', 'Firmware', 'General', null),
(21, 'None', '', 'General', null),
(22, 'Corrosive', 'Elemental Resistance', 'General', null),
(23, 'Cryo', 'Elemental Resistance', 'General', null),
(24, 'Fire', 'Elemental Resistance', 'General', null),
(25, 'Rad', 'Elemental Resistance', 'General', null),
(26, 'Shock', 'Elemental Resistance', 'General', null),
(27, 'Utility 20%/10%', 'Perk', 'General', 1),
(28, 'Utility 28%/15%', 'Perk', 'General', 2),
(29, 'Turtle 40%/10%', 'Perk', 'General', 1),
(30, 'Turtle 65%/15%', 'Perk', 'General', 2),
(31, 'Sturdy 5%/20%', 'Perk', 'General', 1),
(32, 'Sturdy 8%/28%', 'Perk', 'General', 2),
(33, 'Spike Thorns effect damage', 'Perk', 'General', 1),
(34, 'Spike Thorns effect damage x2', 'Perk', 'General', 2),
(35, 'Resistance 17%', 'Perk', 'General', 1),
(36, 'Resistance 22%', 'Perk', 'General', 2),
(37, 'Reflect 15%', 'Perk', 'General', 1),
(38, 'Reflect 30%', 'Perk', 'General', 2),
(39, 'Power Booster 20%/10%', 'Perk', 'General', 1),
(40, 'Power Booster 30%/20%', 'Perk', 'General', 2),
(41, 'Pinpoint 20%/20%/25%', 'Perk', 'General', 1),
(42, 'Pinpoint 28%/28%/35%', 'Perk', 'General', 2),
(43, 'Overshield 10%', 'Perk', 'General', 1),
(44, 'Overshield 15%', 'Perk', 'General', 2),
(45, 'Mag Booster 10%', 'Perk', 'General', 1),
(46, 'Mag Booster 15%', 'Perk', 'General', 2),
(47, 'Health Booster 20%/15%', 'Perk', 'General', 1),
(48, 'Health Booster 30%/25%', 'Perk', 'General', 2),
(49, 'Healthy 10%', 'Perk', 'General', 1),
(50, 'Healthy 25%', 'Perk', 'General', 2),
(51, 'Evasive 5%/10%', 'Perk', 'General', 1),
(52, 'Evasive 8%/15%', 'Perk', 'General', 2),
(53, 'Capacity 25%', 'Perk', 'General', 1),
(54, 'Capacity 50%', 'Perk', 'General', 2),
(55, 'Adaptive 8%/20%', 'Perk', 'General', 1),
(56, 'Adaptive 16%/40%', 'Perk', 'General', 2),
(57, 'Absorb 15%', 'Perk', 'General', 1),
(58, 'Absorb 30%', 'Perk', 'General', 2),
(59, 'Nothing', '', 'General', null),
(60, 'Nothing', '', 'General', null),
(61, 'Nothing', '', 'General', null),
(62, 'Nothing', '', 'General', null),
(63, 'Nothing', '', 'General', null),
(64, 'Risky Boots', 'Firmware', 'General', null),
(1, 'Vagabond 28%', 'Perk', 'Energy', 2),
(2, 'Shield Booster 10%/13%', 'Perk', 'Energy', 1),
(3, 'Shield Booster 15%/18%', 'Perk', 'Energy', 2),
(4, 'Berserker 20%', 'Perk', 'Energy', 1),
(5, 'Berserker 28%', 'Perk', 'Energy', 2),
(6, 'Siphon 5%', 'Perk', 'Energy', 1),
(7, 'Siphon 10%', 'Perk', 'Energy', 2),
(8, 'Trigger Happy 20%/20%', 'Perk', 'Energy', 1),
(9, 'Trigger Happy 28%/28%', 'Perk', 'Energy', 2),
(10, 'Vagabond 28%', 'Perk', 'Energy', 2),
(11, 'Nova', 'Perk', 'Energy', 1),
(12, 'Fleeting 20%', 'Perk', 'Energy', 1),
(13, 'Fleeting 28%', 'Perk', 'Energy', 2),
(14, 'Brimming 149', 'Perk', 'Energy', 1),
(15, 'Brimming 260', 'Perk', 'Energy', 2),
(16, 'Amp 20%/50%', 'Perk', 'Energy', 1),
(17, 'Amp 28%/100%', 'Perk', 'Energy', 2),
(18, 'Recharge Rate 20%', 'Perk', 'Energy', 1),
(19, 'Recharge Rate 30%', 'Perk', 'Energy', 2),
(20, 'Recharge delay -10%', 'Perk', 'Energy', 1),
(21, 'Recharge Delay -20%', 'Perk', 'Energy', 2),
(22, 'Nothing', '', 'Energy', null),
(23, 'Nothing', '', 'Energy', null),
(24, 'Nothing', '', 'Energy', null),
(25, 'Nothing', '', 'Energy', null),
(26, 'Nothing', '', 'Energy', null),
(27, 'Vagabond 20%', 'Perk', 'Energy', 1),
(28, 'Unknown', '', 'Energy', null),
(29, 'Unknown', '', 'Energy', null),
(30, 'Unknown', '', 'Energy', null),
(1, 'Scavenger 20%', 'Perk', 'Armour', 2),
(2, 'Reinforced Grants overshield', 'Perk', 'Armour', 1),
(3, 'Reinforced Grants more overshield', 'Perk', 'Armour', 2),
(4, 'Positive Reinforcement 15%', 'Perk', 'Armour', 1),
(5, 'Positive Reinforcement 25%', 'Perk', 'Armour', 2),
(6, 'Mini Nova nova damage', 'Perk', 'Armour', 1),
(7, 'Mini Nova more nova damage', 'Perk', 'Armour', 2),
(8, 'Missile Swarm 2 missiles for 744', 'Perk', 'Armour', 1),
(9, 'Missile Swarm 3 missiles for 1487', 'Perk', 'Armour', 2),
(10, 'Knockback 30%', 'Perk', 'Armour', 1),
(11, 'Knockback 40%', 'Perk', 'Armour', 2),
(12, 'Heavy Plating 20%', 'Perk', 'Armour', 1),
(13, 'Heavy Plating 35%', 'Perk', 'Armour', 2),
(14, 'Spunky 10%', 'Perk', 'Armour', 1),
(15, 'Spunky 20%', 'Perk', 'Armour', 2),
(16, 'Bladed 13%', 'Perk', 'Armour', 1),
(17, 'Bladed 20%', 'Perk', 'Armour', 2),
(18, 'Armor Strength 10%', 'Perk', 'Armour', 1),
(19, 'Armor Strength 20%', 'Perk', 'Armour', 2),
(20, 'Armor Segment +1', 'Perk', 'Armour', 1),
(21, 'Armor Segment +1', 'Perk', 'Armour', 2),
(22, 'Flanking 10%', 'Perk', 'Armour', 1),
(23, 'Flanking 18%', 'Perk', 'Armour', 2),
(24, 'Boxer 15%', 'Perk', 'Armour', 1),
(25, 'Boxer 25%', 'Perk', 'Armour', 2),
(26, 'White Item Card', 'Slot 1 lookup', 'Armour', null),
(27, 'Green Item Card', 'Slot 1 lookup', 'Armour', null),
(28, 'Blue Item Card', 'Slot 1 lookup', 'Armour', null),
(29, 'Purple Item Card', 'Slot 1 lookup', 'Armour', null),
(30, 'Leg Item Card', 'Slot 1 lookup', 'Armour', null),
(31, 'Scavenger 10%', 'Perk', 'Armour', 1);

insert into unique_shields 
(id, manufacturer, unique_perk, shield_name)
values 
(1, 'Maliwan', 'Vintage', 'Extra Medium'),
(8, 'Maliwan', 'Phyosis', 'Pandoran Memento'),
(6, 'Vladof', 'Refreshments', 'Hoarder'),
(8, 'Vladof', 'Bareknuckle', 'Heavyweight'),
(6, 'Tediore', 'Shield Boi', 'Principal'),
(9, 'Tediore', 'Bininu', 'Timekeeper''s New Shield'),
(1, 'Order', 'Glass', 'Cindershelly'),
(2, 'Order', 'Direct Current', 'Protean Cell'),
(6, 'Ripper', 'Short Circuit', 'Sparky Shield'),
(8, 'Ripper', 'Overshield Eater', 'Watts 4 Dinner'),
(7, 'Jakobs', 'Vintage', 'Oak-Aged Cask'),
(8, 'Jakobs', 'Shellot Shell', 'Onion'),
(6, 'Daedalus', 'Wings of Grace', 'Guardian Angel'),
(8, 'Daedalus', 'Power Play', 'Super Soldier'),
(6, 'Torgue', 'Bundled', 'Firewerks'),
(9, 'Torgue', 'Sisyphusian', 'Compleation');